### ISSUE TITLE
Fax an HTML File with this library

### ISSUE THREAD

**Issue by OgaBoss** [interfax/interfax-php#8] opened 2017-04-25 22:11 UTC
Hello, please i would love to know how i can fax an html file using the library.
I tried this 
`$interfax = new Client(['username' => 'Abolaji', 'password' => 'Abolaji']);`
`$fax = $interfax->deliver(['faxNumber' => '+11111111112', 'file'  => ROOT.DS.'fax.html']);`
`var_dump($fax);`

And i got this error

![screen shot 2017-04-25 at 11 07 50 pm](https://cloud.githubusercontent.com/assets/16806901/25409993/5b7446de-2a0c-11e7-97d5-530474a3f7b5.png)

Please help will really be appreciated.
Thank you

**Comment by splatEric** [comment] 2017-04-26 08:11
I'd suggest taking a look at the exception documentation in the README:

https://github.com/interfax/interfax-php#exceptions

If you wrap your code in a try/catch as is shown in the example, you will
be able to output more detail as to exactly what the problem is. Feel free
to paste the results back into this issue if you need assistance
interpreting it.

As a side note, if that is your real account password, I would suggest you
change it on your account to avoid your account being used by other parties.

**Comment by OgaBoss** [comment] 2017-04-26 15:18
@splatEric Thank you for the swift response, i did as you said, and this is what i got now
![screen shot 2017-04-26 at 4 15 53 pm](https://cloud.githubusercontent.com/assets/16806901/25442045/d9cc6ac2-2a9b-11e7-9799-f3b2465bbc22.png)

Please what could be the issue ?
Thank you.

**Comment by splatEric** [comment] 2017-04-26 15:25
That looks like a firewall issue to me ... check you can make requests to
port 443, and try a manual connection check to interfax server as well if
you can (depends on whether you have command line access or not I guess):

telnet rest.interfax.net 443

**Comment by eyalnevo** [comment] 2017-04-28 18:12
@OgaBoss I wanted to check with you if you were able to resolve the issue or if you require further assistance.

**Comment by andela-oadebayo** [comment] 2017-04-28 18:33
@eyalnevo, Thanks for reaching out, it turns out that for some reason port 443 is not open on my Mac, thus it cannot connect. Still looking on a fix for this. Thank you.

**Comment by eyalnevo** [comment] 2017-04-28 18:40
OK - I am glad to hear that you have found what is causing it. I hope you will find a way to fix it.

**Closed as completed by eyalnevo** 2017-04-28 18:40 UTC
